home:
    path: /
    defaults: { _controller: App\Controller\DefaultController::index }
    options:
        sitemap: true

app_login:
    path: /login
    defaults: { _controller: App\Controller\SecurityController::login }

app_logout:
    path: /logout
    defaults: { _controller: App\Controller\SecurityController::logout }

app_forgot_password_request:
    path: /reset-password
    defaults: { _controller: App\Controller\ResetPasswordController::request }

app_check_email:
    path: /reset-password/check-email
    defaults: { _controller: App\Controller\ResetPasswordController::checkEmail }

app_reset_password:
    path: /reset-password/reset/{token}
    defaults: { _controller: App\Controller\ResetPasswordController::reset }
    
contact:
    path: /contact
    defaults: { _controller: App\Controller\ContactController::index }

admin:
    path: /admin
    defaults: { _controller: App\Controller\Admin\DashboardController::index }

contact_show:
    path: /admin/contact/{id}
    methods: GET|POST
    defaults: { _controller: App\Controller\Admin\DashboardController::show }

contact_delete:
    path: /admin/contact-delete/{id}
    methods: POST
    defaults: { _controller: App\Controller\Admin\DashboardController::delete }

answer_delete:
    path: /admin/answer-delete/{id}
    methods: POST
    defaults: { _controller: App\Controller\Admin\DashboardController::deleteAnswer }
    
page:
    path: /{slug}
    defaults: { _controller: App\Controller\DefaultController::showPage }
